config/routes.rb
Onthego::Application.routes.draw do

  scope module: 'biz' do
    resources :sellers
  end

  resources :sessions, only: [:new, :create, :destroy]

  match '/signin', to: 'sessions#new', via: 'get'

  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/gas-stations', to: 'pages#gas_stations', via: 'get', as: :gas_stations

  match '/movies', to: 'pages#movies', via: 'get', as: :movies

  match '/hotels', to: 'pages#hotels', via: 'get', as: :hotels

  root "pages#home"

  

end

app/models/seller.rb
class Seller < ActiveRecord::Base
	has_secure_password

	# Constants
	EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
	# Callbacks
	before_save { self.email = email.downcase }
	before_create :create_remember_token

	# Validations
	# :name
	# :email
	# :password
	validates :name, presence: true, length: { maximum: 50	 }
	validates :email, presence: true, format: { with: EMAIL_FORMAT }, uniqueness: { case_sensitive: false }
	validates :password, length: { minimum: 6 }


	def Seller.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def Seller.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = Seller.digest(Seller.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/biz/sellers_controller.rb
class Biz::SellersController < ApplicationController
	def new
		@seller = Seller.new
  	end
  
  	def show
  		@seller = Seller.find(params[:id])
  		@title = "#{@seller.name} : Profile"
  	end

  	def create
  		#@seller = Seller.new(params[:seller])
  		@seller = Seller.new(seller_params)
  		if @seller.save
        sign_in @seller
  			flash[:success] = "Welcome to OnTheGo!"
  			redirect_to @seller
  		else
  			render 'new'
  		end
  	end

  	private

  	def seller_params
  		params.require(:seller).permit(:name, :email, :password, :password_confirmation)
  	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		@page = "home"
		gon.lat = 28.57
		gon.lng = 77.32
		hostname = request.host_with_port()
		gas_station_url = "http://"+hostname+"/gas-stations"
		movies_url = "http://"+hostname+"/movies"
		hotels_url = "http://"+hostname+"/hotels"
		coupons_url = "http://"+hostname+"/coupons"
		gon.heading = "Within 5 miles of your location"
		@hostname = request.host
		gon.infoWindowContent = '<div class="infowindow">'+
      	'<div id="bodyContent">'+


      	'<div class="panel panel-primary">'+
  			'<div class="panel-heading"><big>Offers within 5 miles...</big></div>'+
  			'<table class="table">'+
				'<tr>'+
					'<td align="center">'+
						'<a href="http://www.latrattoriawv.com/10-off-coupon/"><img src="'+coupons_url+'/coupon_1.jpg"/></a>'+
					'</td>'+
					'<td align="center">'+
						'<a href="http://www.partycity.com/category/entertaining+serving.do"><img src="'+coupons_url+'/coupon_2.jpg"/></a>'+
					'</td>'+
					'<td align="center">'+
						'<a href="http://www.partycity.com/category/entertaining+serving.do"><img src="'+coupons_url+'/coupon_3.jpg"/></a>'+
					'</td>'+
				'</tr>'+
			'</table>'+
			'<table class="table">'+
				'<tr><td align="left">'+
					'<a href="">7 more offers!</a>'+
				'</td></tr>'+
			'</table>'+
		'</div>'+


		'<div class="panel panel-info">'+
  			'<div class="panel-heading"><b>Around you...</b></div>'+
  			'<ul class="list-group">'+
    			'<li class="list-group-item"><a href="'+gas_station_url+'"><big>3 gas stations</big></a></li>'+
    			'<li class="list-group-item"><a href=""><big>5 restaurants</big></a></li>'+
    			'<li class="list-group-item"><a href="'+movies_url+'"><big>1 movie theatre</big></a></li>'+
    			'<li class="list-group-item"><a href="'+hotels_url+'"><big>3 hotels</big></a></li>'+
  			'</ul>'+
		'</div>'+
      '</div>'+
      '</div>'

		
	end

	def gas_stations
		@page = "gas"
		gon.hostname = request.host_with_port()


		gon.lat = 28.57
		gon.lng = 77.32
		
		latlng = Array.new(3)

		lat = 28.5701
		lng = 77.3201
		latlng[0] = [lat, lng]

		lat = 28.5703
		lng = 77.3202
		latlng[1] = [lat, lng]

		lat = 28.5705
		lng = 77.3189
		latlng[2] = [lat, lng]

		gon.latlng = latlng
		
	end


	def movies
		gon.hostname = request.host_with_port()
		@page = "movie"
		gon.lat = 28.57
		gon.lng = 77.32
		
		gon.theatre_lat = 28.5701
		gon.theatre_lng = 77.3181
		
	end

	def hotels
		@page = "hotel"
		gon.hostname = request.host_with_port()


		gon.lat = 28.57
		gon.lng = 77.32
		
		gon.hotel_lat = 28.5701
		gon.hotel_lng = 77.3181
		
	end

end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  def new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		seller = Seller.find_by(email: params[:session][:email].downcase)
		if seller && seller.authenticate(params[:session][:password])
			# signin the seller
			sign_in seller
			redirect_to seller
		else
			# do not signin the seller
			flash.now[:danger] = "Either your email or your password is incorrect!"
			render 'new'
		end
	end

	def destroy
		if signed_in?
			sign_out
		end
		redirect_to root_url
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(seller)
		remember_token = Seller.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		seller.update_attribute(:remember_token, Seller.digest(remember_token))
		self.current_seller=seller
	end

	def current_seller=(seller)
		@current_seller = seller
	end

	def current_seller
		remember_token = Seller.digest(cookies[:remember_token])
		@current_seller ||= Seller.find_by(remember_token: remember_token)
	end

	def signed_in?
		!current_seller.nil?
	end

	def sign_out
		current_seller.update_attribute(:remember_token, Seller.digest(Seller.new_remember_token))
		cookies.delete(:remember_token)
		self.current_seller = nil
	end
end

app/views/biz/sellers/new.html.erb
<div class = "page-header">
	<h1>Sign up<br /><small> And reach out to people around you!</small></h1>
</div>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@seller, html: { role: "form" }) do |f| %>
		<%= render 'shared/error_messages' %>

		<div class = "form-group">
			<%= f.label :name, "Name of your business", class: "sr-only" %>
			<%= f.text_field :name, class: "form-control input-lg", placeholder: "Name of your business e.g. John's Store" %>
		</div>

		<div class = "form-group">
			<div class="input-group">
				<%= f.label :email, "Your primary email id", class: "sr-only" %>
				<div class="input-group-addon input-lg">@</div>
				<%= f.text_field :email, class: "form-control input-lg", placeholder: "Your primary email id" %>
			</div>
		</div>
		
		<div class = "form-group">
			<%= f.label :password, "Create a password", class: "sr-only" %>
			<%= f.password_field :password, class: "form-control input-lg", placeholder: "Create a password, 6-15 characters long" %>
		</div>
		
		<div class = "form-group">
			<%= f.label :password_confirmation, "Retype password", class: "sr-only" %>
			<%= f.password_field :password_confirmation, class: "form-control input-lg", placeholder: "Please re-type the password (same as above)" %>
		</div>

		<%= f.submit "Create my account", class: "btn btn-lg btn-primary btn-block" %>
		<br /><br />
		<div><%= link_to "Already have an account? Login here!", signin_path %></div>
	</div>

<% end %>
</div>

app/views/biz/sellers/show.html.erb
<div class = "page-header">
	<h1><%= @seller.name %></h1>
</div>

<div class="row">
	<div class="col-sm-6 col-md-4">
    	<div class="thumbnail">
    		<div class="place-icon"></div>
    		<div class="caption">
      			<h3>My places</h3>
        		<p>...</p>
        		<p><a href="#" class="btn btn-primary" role="button">Add a place</a></p>
      		</div>
    	</div>
  	</div>
  	<div class="col-sm-6 col-md-4">
    	<div class="thumbnail">
      		<div class="campaign-icon"></div>
    		<div class="caption">
      			<h3>My campaigns</h3>
        		<p>...</p>
        		<p><a href="#" class="btn btn-primary" role="button">New campaign</a></p>
      		</div>
    	</div>
  	</div>
	<div class="col-sm-6 col-md-4">
    	<div class="thumbnail">
    		<div class="insight-icon"></div>
      		<div class="caption">
      			<h3>Insights</h3>
        		<p>...</p>
        		<p><a href="#" class="btn btn-primary" role="button">View all</a></p>
      		</div>
    	</div>
  	</div>
  	<div class="col-sm-6 col-md-4">
    	<div class="thumbnail">
      		<div class="template-icon"></div>
      		<div class="caption">
      			<h3>Templates</h3>
        		<p>...</p>
        		<p><a href="#" class="btn btn-primary" role="button">New template</a></p>
      		</div>
    	</div>
  	</div>
  	<div class="col-sm-6 col-md-4">
    	<div class="thumbnail">
      		<div class="users-icon"></div>
      		<div class="caption">
      			<h3>Users</h3>
        		<p>...</p>
        		<p><a href="#" class="btn btn-primary" role="button">Add new user</a></p>
      		</div>
    	</div>
  	</div>
	<div class="col-sm-6 col-md-4">
    	<div class="thumbnail">
      		<div class="api-icon"></div>
      		<div class="caption">
      			<h3>APIs</h3>
        		<p>...</p>
        		<p><a href="#" class="btn btn-primary" role="button">Manage</a></p>
      		</div>
    	</div>
  	</div>
  	<div class="col-sm-6 col-md-4">
    	<div class="thumbnail">
      		<div class="settings-icon"></div>
      		<div class="caption">
      			<h3>Accounts & settings</h3>
        		<p>...</p>
        		<p><a href="#" class="btn btn-primary" role="button">Edit</a></p>
      		</div>
    	</div>
  	</div>
</div>

app/views/layouts/_footer.html.erb
<div id="sitefooter" class="row">
	<div class="col-lg-12">
		<hr>
		<p class="center"><small>© 2014 OnTheGo</small></p>
		<p class="social-links center">
			<a href="https://www.facebook.com/" target="_blank" data-toggle="tooltip" data-placement="top" title="" data-original-title="Facebook"><i class="fa fa-facebook"></i></a> &nbsp; 
			<a href="https://twitter.com/" target="_blank" data-toggle="tooltip" data-placement="top" title="" data-original-title="Twitter"><i class="fa fa-twitter"></i></a> &nbsp; 
			<a href="mailto:j" target="_blank" data-toggle="tooltip" data-placement="top" title="" data-original-title="Email"><i class="fa fa-envelope-o"></i></a>
		</p>
	</div>
</div>

app/views/layouts/_header.html.erb
	<header class="navbar  navbar-fixed-top navbar-inverse">
		<div class="container">
			<div class="navbar-header">
				<%= link_to "OnTheGo", root_path, id:"logo" %>
			</div>
			<nav class="sitenav collapse navbar-collapse bs-navbar-collapse" role="navigation">
				<ul class="nav nav-tabs pull-right" role="tablist">

  					<li class="dropdown">
    					<a class="dropdown-toggle" data-toggle="dropdown" href="#">
      						Select category <span class="caret"></span>
    					</a>
    					<ul class="dropdown-menu" role="menu">
    						<li><%= link_to "Gas stations", gas_stations_path %></li>
							<li><%= link_to "Movies", movies_path %></li>
							<li><%= link_to "Hotels", hotels_path %></li>
							<li><%= link_to "Saloon", '#' %></li>
							<li><%= link_to "All options", '#' %></li>
							<li class="divider"></li>
							<li><%= link_to "Search", '#'%></li>
							<li><%= link_to "Home", root_path %></li>
    					</ul>
  					</li>
				</ul>
			</nav>
			
		</div>
	</header>

app/views/layouts/_shim.html.erb
	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
		<script src="scripts/html5shiv.js"></script>
		<script src="scripts/respond.min.js"></script>
		<style>.container {max-width: 960px}</style>
	<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>OnTheGo - Find places of interest around you</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<link href="https://fonts.googleapis.com/css?family=Julius+Sans+One|Source+Sans+Pro:200|Squada+One" rel="stylesheet" type="text/css">

	<%= include_gon %>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  	<%= csrf_meta_tags %>
	
  	<%= render 'layouts/shim' %>
  	<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDY0kkJiTPVd2U7aTOAwhc9ySH6oHxOIYM&sensor=false">
	</script>

	<%= render "mapscripts/#{@page}" %>

	
</head>

<body>
	<%= render 'layouts/header' %>
		<% flash.each do |key, value| %>
        	<div class="alert alert-<%= key %> center" role="alert"><%= value %></div>
      	<% end %>
		<%= yield %>
</body>
</html>

app/views/mapscripts/_gas.html.erb
<script>

	function initialize() {
		var myLatLng = new google.maps.LatLng(gon.lat, gon.lng);

		var mapProp = {
			center: myLatLng,
  			zoom:18,
  			panControl: false,
  			zoomControl: false,
  			mapTypeId:google.maps.MapTypeId.ROADMAP
  		};
				
		var map=new google.maps.Map(document.getElementById("map-canvas"), mapProp);

		var contentString = "This is a gas station!";

		var infowindow = new google.maps.InfoWindow({
			content: contentString
		});
		var gas_station_icon_url = "http://" + gon.hostname + "/icons/gas_station_24X24.png"

		for (var x = 0; x < gon.latlng.length; x++) {
			var position = new google.maps.LatLng(gon.latlng[x][0], gon.latlng[x][1]);
			var marker = new google.maps.Marker({
				position: position,
				map: map,
				icon: gas_station_icon_url
			});
			google.maps.event.addListener(marker, 'mouseover', function(){
				infowindow.open(map, this);
			});
		}

	}
	google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/mapscripts/_home.html.erb
<script>

		function initialize()
			{
				var myLatLng = new google.maps.LatLng(gon.lat, gon.lng);

				var mapProp = {
					center: myLatLng,
  					zoom:12,
  					panControl: false,
  					zoomControl: false,
  					mapTypeId:google.maps.MapTypeId.ROADMAP
  				};
				
				var map=new google.maps.Map(document.getElementById("map-canvas"), mapProp);

				var contentString = gon.infoWindowContent;

				var infoWindow = new google.maps.InfoWindow({ 
					content: contentString
				});

				var marker = new google.maps.Marker({
					position: myLatLng,
					map: map,
					title: gon.heading
				});

				infoWindow.open(map, marker);
			}

			google.maps.event.addDomListener(window, 'load', initialize);
	</script>

app/views/mapscripts/_hotel.html.erb
<script>

	function initialize() {
		var myLatLng = new google.maps.LatLng(gon.lat, gon.lng);

		var position = new google.maps.LatLng(gon.hotel_lat, gon.hotel_lng);

		var mapProp = {
			center: position,
  			zoom:12,
  			panControl: false,
  			zoomControl: false,
  			mapTypeId:google.maps.MapTypeId.ROADMAP
  		};
				
		var map=new google.maps.Map(document.getElementById("map-canvas"), mapProp);


		var hotel_icon_url = "http://" + gon.hostname + "/icons/hotel_24X24.png"
		var gas_station_icon_url = "http://" + gon.hostname + "/icons/gas_station_48X48.png"
		var gas_station_url = "http://" + gon.hostname + "/gas-stations"
		var theatre_url = "http://" + gon.hostname + "/movies"
		var park_icon_url = "http://" + gon.hostname + "/icons/park_48X48.png"
		var bar_icon_url = "http://" + gon.hostname + "/icons/bar_48X48.png"
		var theatre_icon_url = "http://" + gon.hostname + "/icons/theatre_48X48.png"
		var boxty_image_url = "http://" + gon.hostname + "/images/boxty_100X100.png"
		var room_1_image_url = "http://" + gon.hostname + "/images/room_1.jpg"
		var room_2_image_url = "http://" + gon.hostname + "/images/room_2.jpg"
		var room_3_image_url = "http://" + gon.hostname + "/images/room_3.jpg"



		var marker = new google.maps.Marker({
			position: position,
			map: map,
			icon: hotel_icon_url
		});

		var contentString = '<div class="infowindow">'+
      		
				'<div class="panel panel-primary">'+
  					'<div class="panel-heading"><big>The Eden (2 Stars)</big></div>'+
  					'<p style="color:grey;">Last updated: About 4 hours ago</p>'+
  					'<table class="table">'+
						'<tr>'+
							'<td align="center">'+
								'<img src='+ room_1_image_url+'/>'+
							'</td>'+
							'<td align="center">'+
								'<img src='+ room_2_image_url+'/>'+
							'</td>'+
							'<td align="center">'+
								'<img src='+ room_3_image_url+'/>'+
							'</td>'+
						'</tr>'+
						'<tr>'+
							'<td align="center">'+
								'<p><a href="">Premium King</a></p>'+						
							'</td>'+
							'<td align="center">'+
								'<p><a href="">Standard Queen</a></p>'+						
							'</td>'+
							'<td align="center">'+
								'<p><a href="">Deluxe Twin</a></p>'+						
							'</td>'+
						'</tr>'+
						'<tr>'+
							'<td align="center">'+
								'<p style="color:red;text-decoration:line-through;">INR 2900</p>'+						
							'</td>'+
							'<td align="center">'+
								'<p style="color:red;text-decoration:line-through;">INR 2500</p>'+						
							'</td>'+
							'<td align="center">'+
								'<p style="color:red;text-decoration:line-through;">INR 2000</p>'+						
							'</td>'+
						'</tr>'+
						'<tr>'+
							'<td align="center">'+
								'<p style="color:green;"><big>INR 2700</big></p>'+						
							'</td>'+
							'<td align="center">'+
								'<p style="color:green;"><big>INR 2300</big></p>'+						
							'</td>'+
							'<td align="center">'+
								'<p style="color:green;"><big>INR 1800</big></p>'+						
							'</td>'+
						'</tr>'+
						'<tr>'+
							'<td align="center">'+
								'<p><a href="">Book this room</a></p><p>Available: 3</p>'+						
							'</td>'+
							'<td align="center">'+
								'<p><a href="">Book this room</a></p><p>Available: 8</p>'+						
							'</td>'+
							'<td align="center">'+
								'<p><a href="">Book this room</a></p><p>Available: 5</p>'+						
							'</td>'+
						'</tr>'+
					'</table>'+
				'</div>'+
				'<div class="panel panel-info">'+
  					'<div class="panel-heading"><b>Chef special today...</b></div>'+
  					'<table class="table">'+
						'<tr>'+
							'<td align="left">'+
								'<img src='+ boxty_image_url+'/>'+						
							'</td>'+
							'<td align="left">'+
								'<p>A traditional Irish potato pancake, its finely grated raw potato and mashed potato mixed together with flour, baking soda, buttermilk and occasionally egg, then cooked like a pancake on a griddle pan.</p>'+
								'<p><a href="http://en.wikipedia.org/wiki/Boxty">Know more</a></p>'+						
							'</td>'+
						'</tr>'+
					'</table>'+
				'</div>'+
				'<div class="panel panel-info">'+
  					'<div class="panel-heading"><b>Whats around...</b></div>'+
  					'<table class="table">'+
						'<tr>'+
							'<td align="center">'+
								'<a href="'+gas_station_url+'">'+'<img src='+ gas_station_icon_url+'/>'+'</a>'+						
							'</td>'+
							'<td align="center">'+
								'<a href="'+theatre_url+'">'+'<img src='+ theatre_icon_url+'/>'+'</a>'+												'</td>'+
							'<td align="center">'+
								'<img src='+ park_icon_url+'/>'+						
							'</td>'+
							'<td align="center">'+
								'<img src='+ bar_icon_url+'/>'+						
							'</td>'+
						'</tr>'+
					'</table>'+
				'</div>'+

      	'</div>'

		var infowindow = new google.maps.InfoWindow({
			content: contentString
		});

      google.maps.event.addListener(marker, 'mouseover', function(){
				infowindow.open(map, marker);
			});


	}

			google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/mapscripts/_movie.html.erb
<script>

	function initialize() {
		var myLatLng = new google.maps.LatLng(gon.lat, gon.lng);

		var position = new google.maps.LatLng(gon.theatre_lat, gon.theatre_lng);

		var mapProp = {
			center: position,
  			zoom:12,
  			panControl: false,
  			zoomControl: false,
  			mapTypeId:google.maps.MapTypeId.ROADMAP
  		};
				
		var map=new google.maps.Map(document.getElementById("map-canvas"), mapProp);


		var theatre_icon_url = "http://" + gon.hostname + "/icons/theatre_24X24.png"

		var marker = new google.maps.Marker({
			position: position,
			map: map,
			icon: theatre_icon_url
		});

		var contentString = '<div class="infowindow">'+
      		
				'<div class="panel panel-primary">'+
  					'<div class="panel-heading"><big>Next change @ 3:30 PM</big></div>'+
  					'<table class="table">'+
						'<tr>'+
							'<td align="center">'+
								'<object data="http://www.youtube.com/embed/hqiNL4Hn04A"></object>'+						
							'</td>'+
						'</tr>'+
					'</table>'+
					'<table class="table">'+

						'<tr>'+
							'<td align="left">'+
								'<a href="" style="color:red;"><big>Running out!</big></a>'+
							'</td>'+
							'<td align="left">'+
								'<big>The Man Who Knew Infinity</big>'+
							'</td>'+
							'<td align="left">'+
								'<big>3:40 PM</big>'+
							'</td>'+
						'</tr>'+						
						'<tr>'+
							'<td align="left">'+
								'<a href=""><big>Available</big></a>'+
							'</td>'+
							'<td align="left">'+
								'<big>The Best Magician</big>'+
							'</td>'+
							'<td align="left">'+
								'<big>3:30 PM</big>'+
							'</td>'+
						'</tr>'+
						'<tr>'+
							'<td align="left">'+
								'<a href=""><big>Available</big></a>'+
							'</td>'+
							'<td align="left">'+
								'<big>Iron Man 3</big>'+
							'</td>'+
							'<td align="left">'+
								'<big>3:50 PM</big>'+
							'</td>'+
						'</tr>'+
					'</table>'+
				'</div>'+
				'<div class="panel panel-info">'+
  					'<div class="panel-heading"><b>Offers here...</b></div>'+
  					'<ul class="list-group">'+
    					'<li class="list-group-item"><big>Buy 3 tickets and get the fourth one for <i><em>FREE</em></i>!</big></li>'+
    					'<li class="list-group-item"><big>Buy 2 tickets and your coke + popcorn is on us!</big></li>'+
		  			'</ul>'+
				'</div>'+
      	'</div>'

		var infowindow = new google.maps.InfoWindow({
			content: contentString
		});

      google.maps.event.addListener(marker, 'mouseover', function(){
				infowindow.open(map, marker);
			});


	}

			google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/pages/gas_stations.html.erb
<div id="map-canvas" style="width:100%; height:600px;"></div>

app/views/pages/home.html.erb
<div id="map-canvas" style="width:100%; height:600px;"></div>

app/views/pages/hotels.html.erb
<div id="map-canvas" style="width:100%; height:600px;"></div>

app/views/pages/movies.html.erb
<div id="map-canvas" style="width:100%; height:600px;"></div>

app/views/sellers/new.html.erb
<h1>Sellers#new</h1>
<p>Find me in app/views/sellers/new.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if @seller.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-error">
            The form contains <%= pluralize(@seller.errors.count, "error") %>.
        </div>
        <ul>
            <% @seller.errors.full_messages.each do |msg| %>
                <li>* <%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>